  name: Deploy Content Update
  on:
    push:
      branches: [main]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Vercel Deploy
          run: |
            curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_vzkmTFKjtowGUXBBE2crGTTlXLol/G8SFN64mDH"